// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSzhNBVwSX4fPgFvZQQnRzr_wi_ZJWDJY',
    appId: '1:882672938205:web:730a1aa652db695b503f34',
    messagingSenderId: '882672938205',
    projectId: 'careseva2',
    authDomain: 'careseva2.firebaseapp.com',
    storageBucket: 'careseva2.firebasestorage.app',
    measurementId: 'G-9JE0KGV2S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHlnYu60Xyb7Pr2odsJOFvXKPX1R6Ffq8',
    appId: '1:882672938205:android:a3c1a40fffb64d8d503f34',
    messagingSenderId: '882672938205',
    projectId: 'careseva2',
    storageBucket: 'careseva2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKN-UOJ4OVuMqQ6sfujdscW-XfeeqdMxw',
    appId: '1:882672938205:ios:28707bc90c295107503f34',
    messagingSenderId: '882672938205',
    projectId: 'careseva2',
    storageBucket: 'careseva2.firebasestorage.app',
    iosBundleId: 'com.example.caresevaMobileApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKN-UOJ4OVuMqQ6sfujdscW-XfeeqdMxw',
    appId: '1:882672938205:ios:28707bc90c295107503f34',
    messagingSenderId: '882672938205',
    projectId: 'careseva2',
    storageBucket: 'careseva2.firebasestorage.app',
    iosBundleId: 'com.example.caresevaMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSzhNBVwSX4fPgFvZQQnRzr_wi_ZJWDJY',
    appId: '1:882672938205:web:c4eed02b72aa30d6503f34',
    messagingSenderId: '882672938205',
    projectId: 'careseva2',
    authDomain: 'careseva2.firebaseapp.com',
    storageBucket: 'careseva2.firebasestorage.app',
    measurementId: 'G-SX9V20KS3X',
  );
}
